services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=notion-version-control'
      - 'POSTGRES_PASSWORD=local'
      - 'POSTGRES_USER=local'
    ports:
      - '5432'
